name: Deploy PRODUCTION (emera-game)
on:
  push:
    tags: 
        - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # (Optional) build step if you add one later

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Rsync to /var/www/saleem.net/projects/emera-game
        run: |
          rsync -avz --delete \
            --exclude ".git/" \
            ./ \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/saleem.net/projects/emera-game/
